### ISSUE TITLE
Error when loading save with placed combinator

### ISSUE THREAD

**Issue by Neko14789** [loneguardian/CraftingCombinator#1]
The mod Crafting Combinator Xeraph's Fork (0.3.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event crafting_combinator_xeraph::on_tick (ID 0)
__crafting_combinator_xeraph__/control.lua:257: attempt to compare number with nil
stack traceback:
	__crafting_combinator_xeraph__/control.lua:257: in function <__crafting_combinator_xeraph__/control.lua:255>

**Comment by Neko14789** [comment]
This might be a migration issue with some previous version. I disabled the mod, loaded the map, saved, enabled the mod again, loaded and saved the map again, and I am able to load it correctly.

**Comment by loneguardian** [comment]
does that mean your all the combinators have to be wiped from the save before it can load properly? That is not the desired behaviour.

May I know which version of crafting combinator you tried to migrate from? Would be the best if you can provide the save to reproduce the issue.

**Comment by loneguardian** [comment]
I have tried:
```
original mod -> 0.3.2
0.2.0 -> 0.3.2
0.2.1 -> 0.3.2
0.2.1 -> 0.3.0 -> 0.3.2
0.2.1 -> 0.3.1 -> 0.3.2
```
Methodology was:
1. Start a new map with said mod version.
2. Place a few crafting combinators, place a few recipe combinators.
3. Save the game.
4. Load it up with next mod version, wait for a few seconds (should be equivalent to a few updates cycle per combinator) - no error.

Wasn't able to produce the said bug.
I am considering the option to consolidate all current migrations in the next patch but I will have to make sure it actually addresses your issue, by knowing what actually went wrong.

**Comment by Neko14789** [comment]
I am very sorry, I do not have the save file anymore. :( I will send you one if I have this problem again. Currently, everything is working fine. I only had the combinator placed in a test world, so there was not really anything lost.

**Comment by Neko14789** [comment]
I have found a copy of the save where I do not have the problem (no Combinator build), but the version should be the same or older. With the things I see there, I can tell you that the issue was somewhere where mod version was 0.2.0 or newer, updating to current version (0.3.2). Also, the Factorio map version at that point was 1.1.70-1 or newer. I hope this can help.

**Comment by loneguardian** [comment]
Updated post with two more migration paths that I have tested. Mod did not crash either. I will close this for now until it can be reproduced.
